### ISSUE TITLE
Actualizar README.md

### ISSUE THREAD

**Issue by fjavierlh** [DAMDAWTeam/hi-people#8]
Se puede mejorar la redacción del archivo README.md:
- Faltan algunos símbolos de acentuación.
- Incluir los comandos como bloques de código para mejorar su lectura.
- Incluir un párrafo de cierre tipo "¡Lo has conseguido!"

**Comment by SorianoTech** [comment]
He creado un PR con la corrección de las faltas de ortografía.

**Comment by fjavierlh** [comment]
Cerrado! 😉
